const COL_PRIMARY = "rgb(15, 188, 212)";
const COL_PRIMARY_DARK = "rgb(0, 117, 159)";
const COL_PRIMARY_LIGHT = "rgb(75, 234, 255)";
const COL_BG = "#feeaf8";
const COL_BG_DARK = "#f0c3e3";
const SECONDARY_COLOR = "#b5b5b5";
const MARGIN_MIN = "10px";
const MARGIN_MID = "20px";
const MARGIN_MAX = "30px";
const BOX_SHADOW_ELMS = `box-shadow: 5px 5px 10px -5px ${COL_BG_DARK}`;
const FONT_SIZE = "1.02em";
const FONT_FAMILY = "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif";
const MEDIA_BREAK_POINT = "768px";
const WIDTH_ON_BIG_SCREENS = "80vw";
const MAX_WIDTH_ON_BIG_SCREENS = "980px";

export { COL_PRIMARY, COL_PRIMARY_DARK, COL_PRIMARY_LIGHT, COL_BG, COL_BG_DARK, SECONDARY_COLOR, MARGIN_MIN, MARGIN_MID, MARGIN_MAX, BOX_SHADOW_ELMS, FONT_SIZE, FONT_FAMILY, MEDIA_BREAK_POINT, WIDTH_ON_BIG_SCREENS, MAX_WIDTH_ON_BIG_SCREENS };